#!/usr/bin/env python3
"""Regenerate README.md from project metadata and route data."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
README = ROOT / "README.md"
PACKAGE_JSON = ROOT / "package.json"
ROUTES_JSON = ROOT / "public" / "routes.json"


def load_json(path):
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def command_table(scripts):
    rows = [
        ("npm install", "Install project dependencies."),
        ("npm start", "Start the local Angular dev server."),
        ("npm run routes:update", "Refresh route data from GPX files."),
        ("npm run routes:update:copy", "Refresh routes and fill missing descriptions with OpenAI."),
        ("npm run routes:preview", "Preview GPX route changes without writing routes.json."),
        ("npm run readme:update", "Regenerate this README from project metadata."),
        ("npm run build", "Build the Angular app."),
        ("npm run build:gh-pages", "Build the GitHub Pages version."),
        ("npm run deploy", "Build and publish the site to the gh-pages branch."),
    ]

    available_rows = [row for row in rows if row[0].split("npm run ")[-1] in scripts or row[0] in {"npm install", "npm start"}]

    lines = ["| Command | Purpose |", "| --- | --- |"]
    lines.extend(f"| `{command}` | {purpose} |" for command, purpose in available_rows)
    return "\n".join(lines)


def route_summary(categories):
    lines = ["| Category | Routes | Distance | Ascent |", "| --- | ---: | ---: | ---: |"]
    total_routes = 0
    total_distance = 0.0
    total_ascent = 0

    for category in categories:
        routes = category.get("routes", [])
        distance = sum(float(route.get("distance", 0)) for route in routes)
        ascent = sum(int(route.get("ascent", 0)) for route in routes)
        total_routes += len(routes)
        total_distance += distance
        total_ascent += ascent
        lines.append(
            f"| {category.get('label', category.get('id', 'Routes'))} | "
            f"{len(routes)} | {distance:.1f} km | {ascent:,} m |"
        )

    lines.append(f"| **Total** | **{total_routes}** | **{total_distance:.1f} km** | **{total_ascent:,} m** |")
    return "\n".join(lines)


def route_catalog(categories):
    lines = []

    for category in categories:
        routes = sorted(category.get("routes", []), key=lambda route: route.get("title", ""))
        if not routes:
            continue

        lines.append(f"### {category.get('label', category.get('id', 'Routes'))}")
        lines.append("")
        lines.append("| Route | Distance | Ascent | Max Altitude |")
        lines.append("| --- | ---: | ---: | ---: |")

        for route in routes:
            lines.append(
                f"| {route.get('title', 'Untitled route')} | "
                f"{float(route.get('distance', 0)):.1f} km | "
                f"{int(route.get('ascent', 0)):,} m | "
                f"{int(route.get('maxAltitude', 0)):,} m |"
            )

        lines.append("")

    return "\n".join(lines).rstrip()


def build_readme():
    package = load_json(PACKAGE_JSON)
    routes = load_json(ROUTES_JSON)
    scripts = package.get("scripts", {})
    categories = routes.get("categories", [])

    return f"""# VeloIreland - Cycling Route Guide

An Angular + PrimeNG app for showcasing cycling routes, deployable on GitHub Pages.

> This file is generated by `python update_readme.py`. Run `npm run readme:update` after changing route data, or use the npm scripts below that do it automatically.

## Features

- Dynamic JSON content loaded from `public/routes.json`
- Route data generated from GPX files in `src/assets/gpx_files`
- Long Routes / Short Routes tabs
- Route cards with map image, elevation profile, distance, ascent, max altitude, description, and expanded details
- Responsive layout using Angular and PrimeNG

## Route Summary

{route_summary(categories)}

## Route Catalogue

{route_catalog(categories)}

## Project Structure

```text
src/
+-- app/
|   +-- components/route-card/
|   +-- models/route.model.ts
|   +-- services/routes.service.ts
|   +-- app.component.ts
|   +-- app.config.ts
+-- assets/gpx_files/
|   +-- longRoutes/
|   +-- shortRoutes/
+-- styles.scss
+-- index.html
public/
+-- routes.json
```

## Updating Routes And README

Add or edit GPX files in:

- `src/assets/gpx_files/longRoutes`
- `src/assets/gpx_files/shortRoutes`

Then run:

```bash
npm run routes:update
```

That command refreshes `public/routes.json` and regenerates this README. To preview route changes without writing JSON:

```bash
npm run routes:preview
```

To only refresh the README:

```bash
npm run readme:update
```

## Commands

{command_table(scripts)}

## Local Development

```bash
npm install
npm start
```

Open `http://localhost:4200`.

## Deploy To GitHub Pages

```bash
npm run deploy
```

The deploy workflow refreshes this README, builds the GitHub Pages version, and publishes `dist/cycling-routes/browser` to the `gh-pages` branch.

After the first deploy, go to **Settings -> Pages -> Branch: gh-pages -> Save**.

If GitHub Pages keeps serving an older version after a successful deploy, force a fresh `gh-pages` commit:

```bash
npx gh-pages -d dist/cycling-routes/browser --message "Force GitHub Pages redeploy"
```

Then wait a minute and check `https://<username>.github.io/<repo-name>/routes.json`.

Your site URL will be:

```text
https://<username>.github.io/<repo-name>/
```
"""


def main():
    temporary_readme = README.with_suffix(".md.tmp")
    temporary_readme.write_text(build_readme(), encoding="utf-8", newline="\n")
    temporary_readme.replace(README)
    print(f"Updated: {README}")


if __name__ == "__main__":
    main()
